[package]
name = "discord-osu-bot"
version = "0.1.0"
edition = "2024"

[dependencies]
dotenvy = "0.15.7"
num-format = "0.4.4"
num-traits = "0.2.19"
once_cell = "1.21.3"
poise_macros = { version = "0.6.1" }
poise = { git = "https://github.com/serenity-rs/poise", version = "0.6.1" }
serenity = "0.12.4"
time = "0.3.44"
timeago = "0.5.0"
tokio = { version = "1.48.0", features = ["macros", "rt-multi-thread"] }
tracing = "0.1.41"
rosu-v2 = { git = "https://github.com/MaxOhn/rosu-v2", branch = "main" }
rosu-pp = { git = "https://github.com/MaxOhn/rosu-pp", branch = "main" }
reqwest = "0.12.24"
bytes = "1.10.1"
strum = "0.27.2"
strum_macros = "0.27.2"
regex = "1.12.2"
redis = "1.0.2"
